version: '3.8'
services:
  web:
    build: web
    restart: always
    ports:
      - 5000:5000
    networks:
      - flask_network

  nginx:
    build: nginx
    restart: always
    ports:
      - 80:80
    networks:
      - flask_network
    
networks:
  flask_network:
